from . import start
from . import cancel
from . import main_menu
from . import about
from . import question
from . import price_list
from . import contact
from . import jobs
from . import stilists
from . import recoeding_to_specialist
